### ISSUE TITLE
Discussion wether to make automatic translation abvailable on Weblate

### ISSUE THREAD

**Issue by moWerk** [AsteroidOS/supported-languages#11]
Saving recent matrix discussion to continue here:

lepras:
https://docs.weblate.org/en/latest/admin/machine.html 
is this available for the hosted one? probably not, but it would make the transaltion process breeze -> like the person then just have to preview and make edits

eLtMosen:
Afaiu, this feature was not available when we set up weblate and indeed is worth discussing!
Looking at an example, integrating deepl.com requires a paid api key tho. Might ther be free services among the listed ones?
And i conquer, it might make the translation process faster for someone genuinly understanding a language.
But otoh it might invite people not familiar with a language to still feed the unaltered automatic translations just for completion sake?
See my हिंदी attempt. It looked very convincing to me that its नागरी since google translate and wikipedia suggested it to me.

lepras:
yeah makes sense. But then again if a user actually used the watch in that language and comes about some mistakes, then they can contribute ? lmao, like the project is in very early stages and its not like we have a such scale that we have to be concerned about user wrath IMHO. but your concern is very genuine.
only free viable option seems to be https://github.com/LibreTranslate/LibreTranslate

eLtMosen:
Frankly, i was so convinced its नागरी, only genuine interest in a clean translatation even made me ask back 😅
And you are right with the impact estimation imho. Its a minor concern. Looking at the amount of contributors, enabeling out translate would sure have more positive than hypothiszed negative impact.
So, is there a free and ideally privacy minded api available?

lepras:
It has some instances that provide API without key and only IP block when abused
like this instance -> https://translate.argosopentech.com/
though some instances are down so it is not a reliable thing but this instance seems to backed by a corp so its more likely that it stays, i checked others -> not so reliable

**Comment by lepras** [comment]
Also if there can be some transliteration popup, like i just used this for Hindi: https://indiatyping.com/index.php/english-to-hindi-typing.

I am a native but haven't used keyboard input for it. (can write with hand and read but the keyboard input is a little bit hard for typing)

**Comment by lepras** [comment]
Also docs should mention some tips for speedy translation -> like use zen mode in weblate,  use privacy fronted of google translate (like [this simplytranslate instance](https://simplytranslate.manerakai.com)) for quick reference and some transliteration tool if available.

**Comment by moWerk** [comment]
Too be considered/active
- Weblate is now activated and i will look into what it actually does right now.
- Google, needs some official email or google account to register the free thing and we ned to put 10$ per month upfront and somehow check if its refunded.
- Deepl is completely free up to 500k req/day, -> registration with AOS official email i'd suggest.
- Yandex seems free but api registration or more info only with yandex account.
- MyMemory should be used imo -> needs official email for missuse reports only

Not to consider imo or too much effort
- Glosbe is completely free but has license implications someone would have to clear up.
- Netease and Baidu and youdao are competely chinese, no clue.
- SAP and M$ and ModernMT and Libretranslate are expensive.
- tmserver/Amagama are self hosted, maybe if someone is keen to play with. But not really necessary imho.

**Comment by moWerk** [comment]
Weblates internal translation feature is now activated.
Since all other services require yet another account, i would like to see if this feature already suffices our needs.
Weblate translate searches in all weblate projects for similar translations, which gave very good results when testing german.
Will keep this issue and discussion open.

**Comment by lepras** [comment]
Do we have our own instance set up? if yes we should mention that here -> https://asteroidos.org/wiki/translating-asteroidos/

**Comment by moWerk** [comment]
Closing since the weblate internal auto translate works exceptionally well.
